# This file was generated by GoReleaser. DO NOT EDIT.
cask "gonetia" do
  version "0.1.0"

  on_macos do
    on_arm do
      sha256 "708ae800e89dae16b4727b0955d76cabd4a273a6542004a81634ac9fb34d91a8"
      url "https://github.com/tomholford/gonetia/releases/download/v#{version}/gonetia_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "9630375365ad1e5fec60fd89533e7841a46031242be2c3e212372f2a2b8500bf"
      url "https://github.com/tomholford/gonetia/releases/download/v#{version}/gonetia_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "479f180017e8483b5859edbec0042dc14826d2a796f1d1507a570fd5c22e9cef"
      url "https://github.com/tomholford/gonetia/releases/download/v#{version}/gonetia_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "177c61faccef450e6ad2a1d5f3f664d5def882f2558edd9ca3bd4b9d0d9a9ce7"
      url "https://github.com/tomholford/gonetia/releases/download/v#{version}/gonetia_#{version}_linux_amd64.tar.gz"
    end
  end

  name "gonetia"
  desc "Generate Urbit planet names issuable from a star"
  homepage "https://github.com/tomholford/gonetia"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gonetia"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/gonetia"]
    end
  end

  # No zap stanza required
end
