# This file was generated by GoReleaser. DO NOT EDIT.
cask "remiterm" do
  version "0.1.2"

  on_macos do
    on_arm do
      sha256 "53b9e3a5d60a696b08116e104e7f9d420257f2a6847e6580e6ecb756ea4a368d"
      url "https://github.com/tomholford/remiterm/releases/download/v#{version}/remiterm_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "616797edf19eefada06fd0b97a5072fbf42a794c5152b50ef64ad6aefc056857"
      url "https://github.com/tomholford/remiterm/releases/download/v#{version}/remiterm_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "d126a609e19d59542832e58f603978937072c6cf1fec4d6d8574b39626d7dc49"
      url "https://github.com/tomholford/remiterm/releases/download/v#{version}/remiterm_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "a51ae7279673247068c6d0b08f086f13cf62aa52435287345bfa71ff78ee24ca"
      url "https://github.com/tomholford/remiterm/releases/download/v#{version}/remiterm_#{version}_linux_amd64.tar.gz"
    end
  end

  name "remiterm"
  desc "RemiliaNET global chat in your terminal"
  homepage "https://github.com/tomholford/remiterm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "remiterm"

  postflight_steps do
    on_macos do
      run "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "{{staged_path}}/remiterm"]
    end
  end

  # No zap stanza required
end
