# This file was generated by GoReleaser. DO NOT EDIT.
cask "remiterm" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "91f24b2cf0273a18ae2e660110cc00145fe33d87461e2e806e47aac95efcb734"
      url "https://github.com/tomholford/remiterm/releases/download/v#{version}/remiterm_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "66c4b067bd4199f6e71a3550bbee9e428f3178a9db41b8bab97f8385a3852c18"
      url "https://github.com/tomholford/remiterm/releases/download/v#{version}/remiterm_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "bc3015a857d153a7cb9be78dc733b9774d3754c7c7022101abeef216bb428fba"
      url "https://github.com/tomholford/remiterm/releases/download/v#{version}/remiterm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "53bb45a402060331eae82d5fad1eadff1329a215cd3076976aa80cdbeca3eca4"
      url "https://github.com/tomholford/remiterm/releases/download/v#{version}/remiterm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "remiterm"
  desc "RemiliaNET global chat in your terminal"
  homepage "https://github.com/tomholford/remiterm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "remiterm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/remiterm"]
    end
  end

  # No zap stanza required

end
