# This file was generated by GoReleaser. DO NOT EDIT.
cask "remiterm" do
  version "0.1.0"

  on_macos do
    on_intel do
      sha256 "b316cd674b83892fe2a2a3153ccc01d78dd3251c8309b88412bd75c36e62bf04"
      url "https://github.com/tomholford/remiterm/releases/download/v#{version}/remiterm_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d1e4c79fe7a0278f1b374669334bc98e310295ef72d1dd48c442a5449c362382"
      url "https://github.com/tomholford/remiterm/releases/download/v#{version}/remiterm_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "15ce1a9c806cef75195249f5adadf10208972aca9673043e56a16bb023c86523"
      url "https://github.com/tomholford/remiterm/releases/download/v#{version}/remiterm_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "578c7266a6520a1225bb10e65b5e527a4bfe5c679ecfccba3bdae04f3292ea88"
      url "https://github.com/tomholford/remiterm/releases/download/v#{version}/remiterm_#{version}_linux_arm64.tar.gz"
    end
  end

  name "remiterm"
  desc "RemiliaNET global chat in your terminal"
  homepage "https://github.com/tomholford/remiterm"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "remiterm"

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/remiterm"]
    end
  end

  # No zap stanza required

end
